# Generated by Django 6.0 on 2025-12-08 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a0', models.FloatField()),
                ('a1', models.FloatField()),
                ('a2', models.FloatField()),
                ('a3', models.FloatField(blank=True, null=True)),
                ('r2', models.FloatField()),
                ('points_used', models.PositiveIntegerField()),
                ('use_carbonation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_model', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upv', models.FloatField()),
                ('rh_index', models.FloatField()),
                ('carbonation_depth', models.FloatField(blank=True, null=True)),
                ('core_fc', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_points', to='projects.member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_points', to='projects.project')),
            ],
        ),
    ]
