# Generated by Django 6.0 on 2025-12-08 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_tag', models.CharField(blank=True, max_length=255)),
                ('upv', models.FloatField()),
                ('rh_index', models.FloatField()),
                ('carbonation_depth', models.FloatField(blank=True, null=True)),
                ('estimated_fc', models.FloatField()),
                ('rating', models.CharField(choices=[('GOOD', 'GOOD'), ('FAIR', 'FAIR'), ('POOR', 'POOR')], max_length=10)),
                ('model_used', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='projects.member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='projects.project')),
            ],
        ),
    ]
