# Generated by Django 6.0 on 2025-12-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='member_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
