# Generated by Django 6.0 on 2025-12-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_reading_member_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='member_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Member'),
        ),
    ]
