# Generated by Django 6.0 on 2025-12-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_alter_reading_member_text'),
        ('readings', '0003_report_export_fields'),
    ]

    operations = [
    ]
