# Generated by Django 6.0 on 2025-12-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_merge_20251214_1352'),
        ('readings', '0004_report_media'),
    ]

    operations = [
    ]
